<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5996" started-at="2018-09-18T17:18:39Z" finished-at="2018-09-18T17:18:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5996" started-at="2018-09-18T17:18:39Z" finished-at="2018-09-18T17:18:45Z">
      <class name="com.qa.tests.postAPITest">
        <test-method status="PASS" signature="setUP()[pri:0, instance:com.qa.tests.postAPITest@6d78f375]" name="setUP" is-config="true" duration-ms="17" started-at="2018-09-18T22:48:39Z" finished-at="2018-09-18T22:48:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="FAIL" signature="postAPI()[pri:0, instance:com.qa.tests.postAPITest@6d78f375]" name="postAPI" duration-ms="3594" started-at="2018-09-18T22:48:39Z" finished-at="2018-09-18T22:48:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.qa.tests.postAPITest.postAPI(postAPITest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postAPI -->
        <test-method status="PASS" signature="setUP()[pri:0, instance:com.qa.tests.postAPITest@6d78f375]" name="setUP" is-config="true" duration-ms="1" started-at="2018-09-18T22:48:43Z" finished-at="2018-09-18T22:48:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method status="PASS" signature="postAPI2()[pri:0, instance:com.qa.tests.postAPITest@6d78f375]" name="postAPI2" duration-ms="2340" started-at="2018-09-18T22:48:43Z" finished-at="2018-09-18T22:48:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postAPI2 -->
      </class> <!-- com.qa.tests.postAPITest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
